---

services:
  mysql:
      image: mysql:latest
      container_name: chat-mysql
      expose:
        - "3306"
      environment:
          MYSQL_ROOT_PASSWORD: $DB_PASSWORD
          MYSQL_DATABASE: $DB_NAME
      volumes:
        - test_chat_mysql_vol:/var/lib/mysql
      restart: always
      healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 3s
            timeout: 20s
            retries: 10
  migrator:
    image: migrator_test:local
    container_name: migrator
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
volumes:
  test_chat_mysql_vol:
  